# Generated by Django 4.2 on 2023-04-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True)),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('NB_GSM', models.CharField(max_length=100, null=True)),
                ('pseudo', models.CharField(max_length=100, null=True)),
                ('e_mail', models.EmailField(max_length=100, null=True)),
                ('client_id', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='composteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True)),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('NB_GSM', models.CharField(max_length=100, null=True)),
                ('pseudo', models.CharField(max_length=100, null=True)),
                ('e_mail', models.EmailField(max_length=100, null=True)),
                ('composteur_id', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_projet', models.CharField(max_length=100)),
                ('Nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('NB_GSM', models.IntegerField()),
                ('pseudo', models.CharField(max_length=100)),
                ('e_mail', models.EmailField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
            ],
        ),
    ]
