# Generated by Django 4.2 on 2023-04-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='password',
            field=models.CharField(default='default-password', max_length=200),
        ),
    ]
