# Generated by Django 4.2 on 2023-04-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0002_projet_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
