# Generated by Django 4.2 on 2023-04-25 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0003_alter_projet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 12, 31)),
        ),
        migrations.AddField(
            model_name='projet',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
        ),
    ]
