# Generated by Django 4.2 on 2023-04-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0005_projet_comp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='comp',
        ),
    ]
