# Generated by Django 4.2 on 2023-05-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0008_alter_composteur_nb_gsm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composteur',
            name='NB_GSM',
            field=models.CharField(default='000', max_length=100),
        ),
    ]
