# Generated by Django 4.2 on 2023-05-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0013_alter_composteur_nb_gsm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composteur',
            name='NB_GSM',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
