# Generated by Django 4.2 on 2023-05-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0017_rename_nb_gsm_client_gsm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='GSM',
        ),
        migrations.RemoveField(
            model_name='composteur',
            name='GSM',
        ),
        migrations.AddField(
            model_name='client',
            name='NGSM',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='composteur',
            name='NGSM',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
