# Generated by Django 4.2 on 2023-05-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0018_remove_client_gsm_remove_composteur_gsm_client_ngsm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='NGSM',
            new_name='NB_GSM',
        ),
        migrations.RenameField(
            model_name='composteur',
            old_name='NGSM',
            new_name='NB_GSM',
        ),
    ]
