# Generated by Django 4.2 on 2023-05-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0019_rename_ngsm_client_nb_gsm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composteur',
            name='composteur_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
