# Generated by Django 4.2 on 2023-05-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0020_alter_composteur_composteur_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composteur',
            name='NB_GSM',
            field=models.CharField(default='111', max_length=100, null=True),
        ),
    ]
