# Generated by Django 4.2 on 2023-05-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0021_alter_composteur_nb_gsm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='NB_GSM',
        ),
        migrations.AddField(
            model_name='projet',
            name='GSM',
            field=models.IntegerField(default=0),
        ),
    ]
