# Generated by Django 4.2 on 2023-05-02 10:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0022_remove_projet_nb_gsm_projet_gsm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='GSM',
        ),
        migrations.AddField(
            model_name='projet',
            name='NB_GSM',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='composteur',
            name='NB_GSM',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='composteur',
            name='composteur_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='composteur',
            name='e_mail',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='composteur',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='composteur',
            name='prenom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='composteur',
            name='pseudo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='registre.composteur'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 12, 31)),
        ),
        migrations.AlterField(
            model_name='projet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projet',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
        ),
    ]
