# Generated by Django 4.2 on 2023-05-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0023_remove_projet_gsm_projet_nb_gsm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composteur',
            name='GSM',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
