# Generated by Django 4.2 on 2023-05-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0024_composteur_gsm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composteur',
            name='NB_GSM',
        ),
    ]
