# Generated by Django 4.2 on 2023-04-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_nodes_proj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
