# Generated by Django 4.2 on 2023-04-28 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0004_projet_end_date_projet_start_date'),
        ('map', '0003_alter_nodes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='registre.composteur'),
        ),
    ]
