# Generated by Django 4.2 on 2023-04-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_nodes_comp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodes',
            name='comp',
        ),
    ]
